modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/fanziyun/363changelog/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
logoFile = "assets/${mod_id}/icon.png"
description = '''
更新日志模组 - 在标题界面与暂停界面展示整合包更新日志
'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[4,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "CLIENT"
